name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main # ou master, dependendo da sua branch principal

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Ou a versão do Node.js que você usa

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --project premoldaco-webapp # Substitua pelo ID do seu projeto Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PREMOLDACODEV }} # O nome do secret que você criou